---
title: "Test reading tree"
author: "Bruno Crotman"
date: "01/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(xml2)
library(tidygraph)
library(ggraph)

source("functions.r", encoding = "UTF-8") 


knitr::opts_chunk$set(echo = TRUE)

```

## Introduction 

This is a test, I'm trying to read the abstract syntax tree of a code using PMD rules

```{r, echo=FALSE, message=FALSE, warning=FALSE}

shell(r"(C:\doutorado\AnaliseTwitter4j\pmd\bin/pmd.bat -d C:\doutorado\AnaliseTwitter4j\match_algorithm_description\little-tree -f xml -R C:\doutorado\AnaliseTwitter4j\match_algorithm_description\blockrules\blockrules.xml -reportfile C:\doutorado\AnaliseTwitter4j\match_algorithm_description\oldblock.xml)")


```
    

## Introduction 



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width==10}


extract_piece_of_code <-  function(begin_line, end_line, begin_column, end_column){


    #for debug
    strings_param <- read_lines("little-tree/code.java") %>% str_flatten("\n")
    # begin_line <- 33
    # end_line <- 43
    # begin_column <- 5
    # end_column <- 5

    strings <- str_split(strings_param, pattern = "\n") %>% unlist()
    
    piece <- strings %>% 
        enframe(name = "line", value = "code") %>% 
        filter(
            between(line, begin_line, end_line)
        ) %>% 
        mutate(
            code = case_when(
                   line == begin_line & line == end_line ~ str_sub(code, start = begin_column , end_column),
                   line == begin_line ~  str_sub(code, start = begin_column),
                   line == end_line ~str_sub(code, end = end_column),
                   TRUE ~ code
                )   
        ) %>% 
        pull(code) %>% 
        str_flatten(collapse = "\n") 
    

    piece

            
}



map_rule_small <- tribble(
    
    ~rule,                              ~small_rule,
    "class_or_interface_body",          "class_body",                   
    "class_or_interface_declaration",   "class_decl",
    "class_or_interface_type",          "class_type",
    "compilation_unit",                 "unit",
    "extends_list",                     "extends",
    "implements_list",                  "implements",
    "import_declaration",               "import",
    "method",                           "method",
    "name",                             "name",
    "package",                          "package",
    "type_declaration",                 "type_decl",
    "constructor_declaration",          "constructor",
    "field_declaration",                "field",
    "variable_id",                      "var_id",
    "formal_parameter",                 "param",
    "formal_parameters",                "params",
    "annotation",                       "annotation",
    "block",                            "block",
    "statement",                        "statement",
    "if_statement",                     "if"
    
    
)

code_all_lines <- read_lines("little-tree/code.java")

alerts <- read_pmd_xml("oldblock.xml") %>% 
    replace_na(
        list(
            method = "No method"
        )
    ) %>% 
    left_join(
        map_rule_small,
        by = c("rule")
    ) %>% 
    mutate(
        code = pmap(
            .l =  list(
                #strings_param = str_flatten(code_all_lines, collapse = "\n"), 
                begin_line = beginline, 
                end_line = endline, 
                begin_column = begincolumn, 
                end_column = endcolumn                
            ),
            .f = extract_piece_of_code 
        )
    )


max_column <- max(alerts$endcolumn)

alerts_from <- alerts %>%  rename_all(.funs = ~str_glue("{.x}_from"))

alerts_to <- alerts %>%  rename_all(.funs = ~str_glue("{.x}_to"))

all_edges <- alerts_from %>% 
    crossing(alerts_to) %>% 
    mutate(
        location_begin_from = beginline_from * max_column + begincolumn_from,
        location_begin_to = beginline_to * max_column + begincolumn_to,
        location_end_from = endline_from * max_column + endcolumn_from,
        location_end_to = endline_to * max_column + endcolumn_to
    ) %>% 
    filter(id_alert_from != id_alert_to) %>% 
    filter(
        location_begin_from <= location_begin_to & location_end_from >= location_end_to
    ) %>% 
    select(
        from = id_alert_from,
        to =id_alert_to
    ) 


descendents <- all_edges %>% 
    group_by(from) %>% 
    summarise(n_descendents = n()) 

alerts_sorted <- alerts %>% 
    left_join(
        descendents,
        by = c("id_alert" = "from")
    ) %>% 
    replace_na(
        list(n_descendents = 0 )
    ) %>% 
    arrange(
        desc(n_descendents)
    ) %>% 
    mutate(
        id_alert_old = id_alert,
        id_alert = row_number()
    ) %>%  
    mutate(
        name = case_when(
            small_rule %in% c("name", "class_type","var_id" ) ~ str_glue('{id_alert}:{small_rule}:{code}'),
            TRUE ~ str_glue("{id_alert}:{small_rule}")
        )
    )

map_new_id_alert <- alerts_sorted %>% 
    select(
        id_alert_old,
        id_alert
    )

all_edges_new_id <-  all_edges %>% 
    left_join(
        map_new_id_alert,
        c("from" = "id_alert_old")
    ) %>% 
    mutate(
        from = id_alert
    ) %>% 
    select(-id_alert) %>% 
    left_join(
        map_new_id_alert,
        c("to" = "id_alert_old")
    ) %>% 
    mutate(
        to = id_alert
    ) %>% 
    select(-id_alert) 
    
complete_graph <- create_empty(n = 0, directed = TRUE) %>% 
    bind_nodes(alerts_sorted ) %>% 
    bind_edges(all_edges_new_id) 


graph_dfs_tree <- complete_graph %>% 
    convert(to_dfs_tree , root = 1, mode = "out" )
    

edges <- graph_dfs_tree %>% 
    activate(edges)


ggraph(graph_dfs_tree, layout = "tree" ) +
    geom_edge_link(arrow = arrow(length = unit(2, 'mm')), 
                   end_cap = circle(2, 'mm')) +    
    geom_node_point(
        aes(color = method),
        size = 3
    ) +
    geom_node_text(
       aes(label = id_alert),
       size = 2
    ) +
    geom_node_label(
        aes(label = name),
        label.size = 0.1,
        repel = TRUE,
        size = 2,
        label.padding = 0.1
    ) +
    coord_flip() +
    scale_x_reverse(expand =c(-1.2,1.2)) +
    scale_y_continuous(expand =c(-2,2)) +
    theme(
        aspect.ratio = 0.8  ,
        legend.position = "top" 
    )


    
```

